export const QUERY_KEY = {
  sendPhone: ['sendPhone'],
  profile: (token: string) => ['profile', token],
  primehill: (token: string) => ['primehill', token],
  suggests: (value: string) => ['suggests', 'getSuggests', value],
  organisation: ['organisation'],
  myAddress: ['myAddress'],
  orders: ['orders'],
  allOrganizations: ['allOrganizations'],
  order: (id: string) => ['orders', id],
  banners: ['banners'],
  catalog: (orgID: number) => ['catalog', orgID],
  category: ['category'],
  vacancies: ['vacancies'],
  shiping: ['shiping'],
  bonusesProgram: ['bonus-program'],
  promotions: ['promotions'],
  events: ['events'],
  partnership: ['partnership'],
  minDeliveryPrice: ['minDeliveryPrice'],
  favourites: ['favourites'],
  QA: ['QA'],
  deliveryRules: ['delivery-rules'],
  navigation: ['navigation'],
  news: ['news'],
};
